name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true

  build-ie:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: warrenbuckley/Setup-Nuget@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: nuget install Selenium.WebDriver.IEDriver -Version 3.150.0
    - run: npm install
    - run: npm test
      env:
        BROWSER: ie
